### ISSUE TITLE
Failed to connect to 127.0.0.1 port xxxx: Connection refused

### ISSUE THREAD

**Issue by Toniiiio** [rstudio/webdriver#68]
Unregularly, i get the error `Failed to connect to 127.0.0.1 port xxxx: Connection refused`, where xxxx is the current port number in usage.

As this errors does not show up regularly it is hard to reproduce.
Sometimes i got the feeling handling the session (ses) variable to a function makes this error more likely, so i assigned it to a global variable.

I apologize for not being able to provide a reproducible example and a potential bad description. I am very open to provide more information if needed.

(Not) reproducible error;

```
ses <<- start_phantom()
> ses$readLog()
[1] ""
> ses$go(url = "https://www.google.de")
Fehler in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to 127.0.0.1 port 8263: Connection refused
```

where start_phantom():

```
start_phantom <- function(){
  pjs <- webdriver::run_phantomjs()
  webdriver::Session$new(port = pjs$port)
}

```

**Comment by gaborcsardi** [comment]
I think if you don't keep `pjs`, which has the handle of the phantom.js process, then the process will be killed. So make sure to keep `pjs` around.

**Comment by Toniiiio** [comment]
Thanks so much for the fast reply Gabor! I tested a lot and the error didn´t appear since. If you have the time and its not too much off-topic i would of course be interested why pjs has to be "around" in addition to ses. If not i am still very grateful!

**Comment by gaborcsardi** [comment]
`pjs$process` is the handle of the phantom.js process. You can use it to manipulate that process, should you want to do that, e.g. to check if it is running or terminate it.

This is a `processx::process` object, which has a finalizer, which is called when there are no more references to it and the finalizer terminates the process. Such a finalizer makes sense at the processx level, because it makes sure that there are no stale processes left around. (Stale meaning that you cannot manipulate them from R any more.)

I agree that this can be confusing in webdriver, and the design here is probably not ideal. E.g. the (last?) webdriver process could have a reference in the webdriver package namespace itself, and then you would not need to keep your reference.
